/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package steganografi.gui;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author Kevin
 */
public class GUIStegano extends javax.swing.JFrame {

    /**
     * Creates new form GUIStegano
     */
    public GUIStegano() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelDekrip = new javax.swing.JPanel();
        jButtonSelectImageD = new javax.swing.JButton();
        jLabelDekripImage = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        JLabelDekripMessage = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        JPanelEnkrip = new javax.swing.JPanel();
        jlabelEnkripMessage = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonSelectImageE = new javax.swing.JButton();
        jLabelEnkripImage = new javax.swing.JLabel();
        jButtonEnkrip = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        JPanelCompare = new javax.swing.JPanel();
        JButtonCompare1 = new javax.swing.JButton();
        jLabelImageCompare1 = new javax.swing.JLabel();
        JButtonCompare2 = new javax.swing.JButton();
        jLabelImageCompare2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonSelectImageD.setText("Select Image");
        jButtonSelectImageD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectImageDActionPerformed(evt);
            }
        });

        jLabelDekripImage.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("Dekrip");

        jLabel1.setText("Pesan");

        jButton5.setText("Save File");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDekripLayout = new javax.swing.GroupLayout(jPanelDekrip);
        jPanelDekrip.setLayout(jPanelDekripLayout);
        jPanelDekripLayout.setHorizontalGroup(
            jPanelDekripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDekripLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDekripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDekripLayout.createSequentialGroup()
                        .addComponent(jLabelDekripImage, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jButtonSelectImageD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDekripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JLabelDekripMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelDekripLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanelDekripLayout.setVerticalGroup(
            jPanelDekripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDekripLayout.createSequentialGroup()
                .addGroup(jPanelDekripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDekripLayout.createSequentialGroup()
                        .addComponent(jButtonSelectImageD)
                        .addGap(125, 125, 125)
                        .addComponent(jButton1))
                    .addGroup(jPanelDekripLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanelDekripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDekripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLabelDekripMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDekripImage, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelDekripImage.getAccessibleContext().setAccessibleName("");

        jTabbedPane.addTab("Dekrip", jPanelDekrip);

        jLabel2.setText("Pesan");

        jButtonSelectImageE.setText("Select Image");
        jButtonSelectImageE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectImageEActionPerformed(evt);
            }
        });

        jButtonEnkrip.setText("Enkrip");
        jButtonEnkrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnkripActionPerformed(evt);
            }
        });

        jButton2.setText("Save Image");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelEnkripLayout = new javax.swing.GroupLayout(JPanelEnkrip);
        JPanelEnkrip.setLayout(JPanelEnkripLayout);
        JPanelEnkripLayout.setHorizontalGroup(
            JPanelEnkripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelEnkripLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelEnkripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jlabelEnkripMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPanelEnkripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelEnkripLayout.createSequentialGroup()
                        .addComponent(jButtonSelectImageE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEnkrip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jLabelEnkripImage, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPanelEnkripLayout.setVerticalGroup(
            JPanelEnkripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelEnkripLayout.createSequentialGroup()
                .addGroup(JPanelEnkripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JPanelEnkripLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlabelEnkripMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanelEnkripLayout.createSequentialGroup()
                        .addGroup(JPanelEnkripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSelectImageE)
                            .addComponent(jButtonEnkrip)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEnkripImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Enkrip", JPanelEnkrip);

        JButtonCompare1.setText("Select Image");
        JButtonCompare1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonCompare1ActionPerformed(evt);
            }
        });

        JButtonCompare2.setText("Select Image");
        JButtonCompare2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonCompare2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelCompareLayout = new javax.swing.GroupLayout(JPanelCompare);
        JPanelCompare.setLayout(JPanelCompareLayout);
        JPanelCompareLayout.setHorizontalGroup(
            JPanelCompareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelCompareLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelCompareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelCompareLayout.createSequentialGroup()
                        .addComponent(JButtonCompare1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JButtonCompare2)
                        .addGap(266, 266, 266))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelCompareLayout.createSequentialGroup()
                        .addComponent(jLabelImageCompare1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelImageCompare2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        JPanelCompareLayout.setVerticalGroup(
            JPanelCompareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelCompareLayout.createSequentialGroup()
                .addGroup(JPanelCompareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButtonCompare1)
                    .addComponent(JButtonCompare2))
                .addGap(18, 18, 18)
                .addGroup(JPanelCompareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelImageCompare2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelImageCompare1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Compare", JPanelCompare);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSelectImageEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectImageEActionPerformed
        // TODO add your handling code here:
        final JFileChooser fc = new JFileChooser();
        //In response to a button click:
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File imgfile = fc.getSelectedFile();
            ImageIcon icon = new ImageIcon(imgfile.getPath());
            Image img = icon.getImage();
            img = img.getScaledInstance(jLabelEnkripImage.getWidth(),jLabelEnkripImage.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon newicon = new ImageIcon(img);
            jLabelEnkripImage.setIcon(newicon);
        }
    }//GEN-LAST:event_jButtonSelectImageEActionPerformed

    private void jButtonSelectImageDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectImageDActionPerformed
        // TODO add your handling code here:
        final JFileChooser fc = new JFileChooser();
        //In response to a button click:
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File imgfile = fc.getSelectedFile();
            ImageIcon icon = new ImageIcon(imgfile.getPath());
            Image img = icon.getImage();
            img = img.getScaledInstance(jLabelDekripImage.getWidth(),jLabelDekripImage.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon newicon = new ImageIcon(img);
            jLabelDekripImage.setIcon(newicon);
        }
    }//GEN-LAST:event_jButtonSelectImageDActionPerformed

    private void JButtonCompare1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonCompare1ActionPerformed
        // TODO add your handling code here:
        final JFileChooser fc = new JFileChooser();
        //In response to a button click:
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File imgfile = fc.getSelectedFile();
            ImageIcon icon = new ImageIcon(imgfile.getPath());
            Image img = icon.getImage();
            img = img.getScaledInstance(jLabelImageCompare1.getWidth(),jLabelImageCompare1.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon newicon = new ImageIcon(img);
            jLabelImageCompare1.setIcon(newicon);
        }
    }//GEN-LAST:event_JButtonCompare1ActionPerformed

    private void jButtonEnkripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnkripActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEnkripActionPerformed

    private void JButtonCompare2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonCompare2ActionPerformed
        // TODO add your handling code here:
        final JFileChooser fc = new JFileChooser();
        //In response to a button click:
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File imgfile = fc.getSelectedFile();
            ImageIcon icon = new ImageIcon(imgfile.getPath());
            Image img = icon.getImage();
            img = img.getScaledInstance(jLabelImageCompare2.getWidth(),jLabelImageCompare2.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon newicon = new ImageIcon(img);
            jLabelImageCompare2.setIcon(newicon);
        }
    }//GEN-LAST:event_JButtonCompare2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        PrintWriter writer = null;
        try {
            writer = new PrintWriter("savedchiper.txt", "UTF-8");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(GUIStegano.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(GUIStegano.class.getName()).log(Level.SEVERE, null, ex);
        }
        writer.println(JLabelDekripMessage.getText());
        writer.close();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIStegano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIStegano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIStegano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIStegano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIStegano().setVisible(true);
            }
        });
    }
    private ImageIcon EnkripImageIcon = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonCompare1;
    private javax.swing.JButton JButtonCompare2;
    private javax.swing.JTextField JLabelDekripMessage;
    private javax.swing.JPanel JPanelCompare;
    private javax.swing.JPanel JPanelEnkrip;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonEnkrip;
    private javax.swing.JButton jButtonSelectImageD;
    private javax.swing.JButton jButtonSelectImageE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDekripImage;
    private javax.swing.JLabel jLabelEnkripImage;
    private javax.swing.JLabel jLabelImageCompare1;
    private javax.swing.JLabel jLabelImageCompare2;
    private javax.swing.JPanel jPanelDekrip;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextField jlabelEnkripMessage;
    // End of variables declaration//GEN-END:variables
}
