/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.company;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Kevin
 */
public class GUIStegano extends javax.swing.JFrame {

    /**
     * Creates new form GUIStegano
     */
    public GUIStegano() {
        super("Stegano-tools");
        initComponents();
        this.setResizable(false);
        inputTextRadioButton.setSelected(true);
        selectFileButton.setEnabled(false);
        SpinnerNumberModel model = new SpinnerNumberModel(0.3, 0.09, 0.50, 0.05);
        complexitySpinner.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        embeddingPanel = new javax.swing.JPanel();
        selectImageButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        stegoObjLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        coverObjLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        messageTextArea = new javax.swing.JTextField();
        selectFileButton = new javax.swing.JButton();
        fileHeaderLabel = new javax.swing.JLabel();
        inputTextRadioButton = new javax.swing.JRadioButton();
        inputFileRadioButton = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        complexitySpinner = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        PSNRvalue = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        extractingPanel = new javax.swing.JPanel();
        selectStegoButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        inputStegoLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        decryptedFileHeaderLabel = new javax.swing.JLabel();
        extractedFileHeaderLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        selectImageButton.setText("Select image..");
        selectImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectImageButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Cover-object");

        stegoObjLabel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Stego-object");

        coverObjLabel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Secret message");

        selectFileButton.setText("Select file..");
        selectFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFileButtonActionPerformed(evt);
            }
        });

        inputTextRadioButton.setText("Text");
        inputTextRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTextRadioButtonActionPerformed(evt);
            }
        });

        inputFileRadioButton.setText("File");
        inputFileRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFileRadioButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Stego-key");

        jLabel8.setText("Complexity treshold");

        jLabel9.setText("PSNR : ");

        jCheckBox1.setText("Encrypt message");

        jButton1.setText("Start Embedding");

        javax.swing.GroupLayout embeddingPanelLayout = new javax.swing.GroupLayout(embeddingPanel);
        embeddingPanel.setLayout(embeddingPanelLayout);
        embeddingPanelLayout.setHorizontalGroup(
            embeddingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(embeddingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(embeddingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(embeddingPanelLayout.createSequentialGroup()
                        .addGroup(embeddingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(coverObjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(embeddingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(stegoObjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(embeddingPanelLayout.createSequentialGroup()
                        .addGroup(embeddingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputTextRadioButton)
                            .addComponent(jLabel7)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(messageTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(embeddingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fileHeaderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(embeddingPanelLayout.createSequentialGroup()
                                .addGroup(embeddingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputFileRadioButton)
                                    .addComponent(selectFileButton)
                                    .addComponent(jLabel8)
                                    .addComponent(complexitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(embeddingPanelLayout.createSequentialGroup()
                        .addGroup(embeddingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jCheckBox1)
                            .addComponent(jButton1)
                            .addGroup(embeddingPanelLayout.createSequentialGroup()
                                .addComponent(selectImageButton)
                                .addGap(263, 263, 263)
                                .addComponent(jLabel9)
                                .addGap(7, 7, 7)
                                .addComponent(PSNRvalue)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        embeddingPanelLayout.setVerticalGroup(
            embeddingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(embeddingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(embeddingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(embeddingPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coverObjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(embeddingPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stegoObjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(embeddingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectImageButton)
                    .addComponent(jLabel9)
                    .addComponent(PSNRvalue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(embeddingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputFileRadioButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inputTextRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(embeddingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messageTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(embeddingPanelLayout.createSequentialGroup()
                        .addComponent(selectFileButton)
                        .addGap(11, 11, 11)
                        .addComponent(fileHeaderLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(embeddingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(embeddingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField5)
                    .addComponent(complexitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Embedding", embeddingPanel);

        selectStegoButton.setText("Select image..");
        selectStegoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectStegoButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("Stego-object");

        inputStegoLabel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setText("Stego-key");

        jButton3.setText("Start Extracting");

        jLabel2.setText("Extracted message");

        jLabel3.setText("Decrypted message");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jButton2.setText("Decrypt message");

        jLabel16.setText("Extracted file");

        jLabel17.setText("Original :");

        jLabel18.setText("Decrypted :");

        javax.swing.GroupLayout extractingPanelLayout = new javax.swing.GroupLayout(extractingPanel);
        extractingPanel.setLayout(extractingPanelLayout);
        extractingPanelLayout.setHorizontalGroup(
            extractingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(extractingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(extractingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(extractingPanelLayout.createSequentialGroup()
                        .addGroup(extractingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(extractingPanelLayout.createSequentialGroup()
                                .addComponent(selectStegoButton)
                                .addGap(264, 264, 264)
                                .addComponent(jButton2))
                            .addComponent(jLabel13)
                            .addComponent(jTextField6))
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(extractingPanelLayout.createSequentialGroup()
                        .addGroup(extractingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(inputStegoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(extractingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addGroup(extractingPanelLayout.createSequentialGroup()
                                .addGroup(extractingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(extractingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(extractedFileHeaderLabel)
                                    .addComponent(decryptedFileHeaderLabel))))))
                .addContainerGap())
        );
        extractingPanelLayout.setVerticalGroup(
            extractingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(extractingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(extractingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(extractingPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputStegoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(extractingPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(extractingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(extractedFileHeaderLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(extractingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(decryptedFileHeaderLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(extractingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectStegoButton)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(extractingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Extracting", extractingPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFileButtonActionPerformed
        final JFileChooser fc = new JFileChooser();
        //In response to a button click:
        fc.setCurrentDirectory(new File(System.getProperty("user.dir")));
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            fileHeaderLabel.setText(file.getName());
        }
    }//GEN-LAST:event_selectFileButtonActionPerformed

    private void selectImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectImageButtonActionPerformed
        final JFileChooser fc = new JFileChooser();
        //In response to a button click:
        fc.setCurrentDirectory(new File(System.getProperty("user.dir")));
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File imgfile = fc.getSelectedFile();
            ImageIcon icon = new ImageIcon(imgfile.getPath());
            Image img = icon.getImage();
            img = img.getScaledInstance(coverObjLabel.getWidth(),coverObjLabel.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon newicon = new ImageIcon(img);
            coverObjLabel.setIcon(newicon);
        }
    }//GEN-LAST:event_selectImageButtonActionPerformed

    private void selectStegoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectStegoButtonActionPerformed
        final JFileChooser fc = new JFileChooser();
        //In response to a button click:
        fc.setCurrentDirectory(new File(System.getProperty("user.dir")));
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File imgfile = fc.getSelectedFile();
            ImageIcon icon = new ImageIcon(imgfile.getPath());
            Image img = icon.getImage();
            img = img.getScaledInstance(inputStegoLabel.getWidth(),inputStegoLabel.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon newicon = new ImageIcon(img);
            inputStegoLabel.setIcon(newicon);
        }
    }//GEN-LAST:event_selectStegoButtonActionPerformed

    private void inputTextRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTextRadioButtonActionPerformed
        inputTextRadioButton.setSelected(true);
        inputFileRadioButton.setSelected(false);
        messageTextArea.setEnabled(true);
        selectFileButton.setEnabled(false);
        fileHeaderLabel.setEnabled(false);
    }//GEN-LAST:event_inputTextRadioButtonActionPerformed

    private void inputFileRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFileRadioButtonActionPerformed
        inputTextRadioButton.setSelected(false);
        inputFileRadioButton.setSelected(true);
        messageTextArea.setEnabled(false);
        selectFileButton.setEnabled(true);
        fileHeaderLabel.setEnabled(true);
    }//GEN-LAST:event_inputFileRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIStegano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIStegano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIStegano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIStegano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIStegano().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PSNRvalue;
    private javax.swing.JSpinner complexitySpinner;
    private javax.swing.JLabel coverObjLabel;
    private javax.swing.JLabel decryptedFileHeaderLabel;
    private javax.swing.JPanel embeddingPanel;
    private javax.swing.JLabel extractedFileHeaderLabel;
    private javax.swing.JPanel extractingPanel;
    private javax.swing.JLabel fileHeaderLabel;
    private javax.swing.JRadioButton inputFileRadioButton;
    private javax.swing.JLabel inputStegoLabel;
    private javax.swing.JRadioButton inputTextRadioButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField messageTextArea;
    private javax.swing.JButton selectFileButton;
    private javax.swing.JButton selectImageButton;
    private javax.swing.JButton selectStegoButton;
    private javax.swing.JLabel stegoObjLabel;
    // End of variables declaration//GEN-END:variables
}
